// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "IntakeForward.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

IntakeForward::IntakeForward(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
// Called just before this Command runs the first time
void IntakeForward::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void IntakeForward::Execute() { //TODO: might need to reverse
	Robot::intake->left->Set(1.0);
	Robot::intake->right->Set(-1.0);
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeForward::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void IntakeForward::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IntakeForward::Interrupted() {

}
