// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	std::shared_ptr<frc::Joystick> coDriver;
	std::shared_ptr<frc::JoystickButton> cRStick;
	std::shared_ptr<frc::JoystickButton> cLStick;
	std::shared_ptr<frc::JoystickButton> cRBumper;
	std::shared_ptr<frc::JoystickButton> cLBumper;
	std::shared_ptr<frc::JoystickButton> cY;
	std::shared_ptr<frc::JoystickButton> cX;
	std::shared_ptr<frc::JoystickButton> cB;
	std::shared_ptr<frc::JoystickButton> cA;
	std::shared_ptr<frc::Joystick> driver;
	std::shared_ptr<frc::JoystickButton> dRStick;
	std::shared_ptr<frc::JoystickButton> dLStick;
	std::shared_ptr<frc::JoystickButton> dRBumper;
	std::shared_ptr<frc::JoystickButton> dLBumper;
	std::shared_ptr<frc::JoystickButton> dY;
	std::shared_ptr<frc::JoystickButton> dX;
	std::shared_ptr<frc::JoystickButton> dB;
	std::shared_ptr<frc::JoystickButton> dA;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> getdriver();
	std::shared_ptr<frc::Joystick> getcoDriver();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
