// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<frc::SpeedController> chassisleftA;
	static std::shared_ptr<frc::SpeedController> chassisleftB;
	static std::shared_ptr<frc::SpeedController> chassisleftC;
	static std::shared_ptr<frc::SpeedControllerGroup> chassisleft;
	static std::shared_ptr<frc::SpeedController> chassisrightA;
	static std::shared_ptr<frc::SpeedController> chassisrightB;
	static std::shared_ptr<frc::SpeedController> chassisrightC;
	static std::shared_ptr<frc::SpeedControllerGroup> chassisright;
	static std::shared_ptr<frc::RobotDrive> chassisrobotDrive;
	static std::shared_ptr<frc::Encoder> chassisdriveEncoder;
	static std::shared_ptr<frc::DoubleSolenoid> chassisshifter;
	static std::shared_ptr<frc::SpeedController> elevatorlift;
	static std::shared_ptr<frc::DigitalInput> elevatorswitchBottom;
	static std::shared_ptr<frc::DigitalInput> elevatorswitchTop;
	static std::shared_ptr<frc::SpeedController> intakeleft;
	static std::shared_ptr<frc::SpeedController> intakeright;
	static std::shared_ptr<frc::Servo> intakeservoLeft;
	static std::shared_ptr<frc::Servo> intakeservoRight;
	static std::shared_ptr<frc::Compressor> pressurizerCompressor;
	static std::shared_ptr<frc::DoubleSolenoid> rampleft;
	static std::shared_ptr<frc::DoubleSolenoid> rampright;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<frc::AnalogInput> chassisAnalogEncoder;
	static std::shared_ptr<ADXRS450_Gyro> chassisGyro;
	static void init();
};
#endif
